/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountMenu: typeof import('./src/components/AccountMenu.vue')['default']
    DateTimePicker: typeof import('./src/components/DateTimePicker.vue')['default']
    FabAddButton: typeof import('./src/components/FabAddButton.vue')['default']
    LeftDrawer: typeof import('./src/components/LeftDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TAvatar: typeof import('tdesign-mobile-vue')['Avatar']
    TBreadcrumb: typeof import('tdesign-mobile-vue')['Breadcrumb']
    TBreadcrumbItem: typeof import('tdesign-mobile-vue')['BreadcrumbItem']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TCard: typeof import('tdesign-mobile-vue')['Card']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup']
    TCheckbox: typeof import('tdesign-mobile-vue')['Checkbox']
    TDateTimePicker: typeof import('tdesign-mobile-vue')['DateTimePicker']
    TDialog: typeof import('tdesign-mobile-vue')['Dialog']
    Test: typeof import('./src/components/Test.vue')['default']
    TFab: typeof import('tdesign-mobile-vue')['Fab']
    TForm: typeof import('tdesign-mobile-vue')['Form']
    TFormItem: typeof import('tdesign-mobile-vue')['FormItem']
    TGrid: typeof import('tdesign-mobile-vue')['Grid']
    TGridItem: typeof import('tdesign-mobile-vue')['GridItem']
    TImage: typeof import('tdesign-mobile-vue')['Image']
    TInput: typeof import('tdesign-mobile-vue')['Input']
    TLayout: typeof import('tdesign-mobile-vue')['Layout']
    TList: typeof import('tdesign-mobile-vue')['List']
    TNavbar: typeof import('tdesign-mobile-vue')['Navbar']
    TPicker: typeof import('tdesign-mobile-vue')['Picker']
    TPopup: typeof import('tdesign-mobile-vue')['Popup']
    TSwitch: typeof import('tdesign-mobile-vue')['Switch']
    TTable: typeof import('tdesign-mobile-vue')['Table']
    TTableColumn: typeof import('tdesign-mobile-vue')['TableColumn']
    TTabPanel: typeof import('tdesign-mobile-vue')['TabPanel']
    TTabs: typeof import('tdesign-mobile-vue')['Tabs']
    TTag: typeof import('tdesign-mobile-vue')['Tag']
    UserPicker: typeof import('./src/components/UserPicker.vue')['default']
  }
}
