/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountMenu: typeof import('./src/components/AccountMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAvatar: typeof import('tdesign-mobile-vue')['Avatar']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup']
    TDivider: typeof import('tdesign-mobile-vue')['Divider']
    TFab: typeof import('tdesign-mobile-vue')['Fab']
    TForm: typeof import('tdesign-mobile-vue')['Form']
    TFormItem: typeof import('tdesign-mobile-vue')['FormItem']
    TIcon: typeof import('tdesign-mobile-vue')['Icon']
    TInput: typeof import('tdesign-mobile-vue')['Input']
    TList: typeof import('tdesign-mobile-vue')['List']
    TNavbar: typeof import('tdesign-mobile-vue')['Navbar']
    TPopover: typeof import('tdesign-mobile-vue')['Popover']
    TPopup: typeof import('tdesign-mobile-vue')['Popup']
    TPullDownRefresh: typeof import('tdesign-mobile-vue')['PullDownRefresh']
    TTabPanel: typeof import('tdesign-mobile-vue')['TabPanel']
    TTabs: typeof import('tdesign-mobile-vue')['Tabs']
  }
}
